name: test code

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: install nodejs
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: start app
        run: npm start &

      - name: check if app is running
        run: |
          sleep 5
          curl -f http://localhost:3000 || exit 1