name: variables

on:
  workflow_dispatch:
     inputs:
        environment:
          description: 'run environment'
          required: true
          default: 'test'
          type: choice
          options:
          - test
          - staging
          - production

        version:
          description: 'version of the app'
          required: true
          default: 'v1.0.0'
          type: string

env:
  hash_count: 5

jobs:
  set-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "environment: ${{ inputs.environment }}" 
          echo "APP_VERSION: ${{ inputs.version }}" 
          echo "hash: ${{ env.hash_count }}"

  jobs-sec-var:
    runs-on: ubuntu-latest
    steps:
      - name: sec & vars
        run: |
          echo "repo-sec: ${{ secrets.POOO_SEC }}"
          echo "repo-var: ${{ vars.COUNT }}"

